services:
  frontend:
    build:
      context: ./src/public

    ports:
      - "5174:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["sh", "-c", "npm install --silent && npm run dev -- --host 0.0.0.0"]

  api:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    ports:
      - "5173:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["sh", "-c", "npm install --silent && npm start"]
